#name: Cypress Tests
#
#on: push
#
#jobs:
#  E2E-On-Chrome-Browser:
#    runs-on: ubuntu-latest
#    steps:
#      - name: Checkout
#        uses: actions/checkout@v3
#
#      - name: Chrome
#        uses: cypress-io/github-action@v6
#        timeout-minutes: 10
#        with:
#          build: npm run build
#          start: npm run dev
#          browser: chrome
#
#  E2E-On-Edge-Browser:
#    needs: E2E-On-Chrome-Browser
#    runs-on: ubuntu-latest
#    steps:
#      - name: Checkout
#        uses: actions/checkout@v3
#
#      - name: Chrome
#        uses: cypress-io/github-action@v6
#        timeout-minutes: 10
#        with:
#          build: npm run build
#          start: npm run dev
#          browser: edge
#
#  E2E-On-Firefox-Browser:
#    needs: E2E-On-Edge-Browser
#    runs-on: ubuntu-latest
#    steps:
#      - name: Checkout
#        uses: actions/checkout@v3
#
#      - name: Firefox
#        uses: cypress-io/github-action@v6
#        timeout-minutes: 10
#        with:
#          build: npm run build
#          start: npm run dev
#          browser: firefox
#
#  E2E-On-Electron-Browser:
#    needs: E2E-On-Firefox-Browser
#    runs-on: ubuntu-latest
#    steps:
#      - name: Checkout
#        uses: actions/checkout@v3
#
#      - name: Electron
#        uses: cypress-io/github-action@v6
#        timeout-minutes: 10
#        with:
#          build: npm run build
#          start: npm run dev
#
#
#  Component-On-Chrome-Browser:
#    runs-on: ubuntu-latest
#    steps:
#      - name: Checkout
#        uses: actions/checkout@v3
#
#      - name: Chrome
#        uses: cypress-io/github-action@v6
#        timeout-minutes: 10
#        with:
#          build: npm run build
#          start: npm run dev
#          browser: chrome
#          component: true
#
#  Component-On-Edge-Browser:
#    runs-on: ubuntu-latest
#    steps:
#      - name: Checkout
#        uses: actions/checkout@v3
#
#      - name: Chrome
#        uses: cypress-io/github-action@v6
#        timeout-minutes: 10
#        with:
#          build: npm run build
#          start: npm run dev
#          browser: edge
#          component: true
#
#  Component-On-Firefox-Browser:
#    runs-on: ubuntu-latest
#    steps:
#      - name: Checkout
#        uses: actions/checkout@v3
#
#      - name: Firefox
#        uses: cypress-io/github-action@v6
#        timeout-minutes: 10
#        with:
#          build: npm run build
#          start: npm run dev
#          browser: firefox
#          component: true
#
#  Component-On-Electron-Browser:
#    runs-on: ubuntu-latest
#    steps:
#      - name: Checkout
#        uses: actions/checkout@v3
#
#      - name: Electron
#        uses: cypress-io/github-action@v6
#        timeout-minutes: 10
#        with:
#          build: npm run build
#          start: npm run dev
#          component: true
