name: Cypress Tests

on: push

jobs:
  On-Chrome-Browser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Chrome
        uses: cypress-io/github-action@v6
        timeout-minutes: 10
        with:
          build: npm run build
          start: npm run preview
          browser: chrome

  On-Firefox-Browser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Firefox
        uses: cypress-io/github-action@v6
        timeout-minutes: 10
        with:
          build: npm run build
          start: npm run preview
          browser: firefox

  On-Electron-Browser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Electron
        uses: cypress-io/github-action@v6
        timeout-minutes: 10
        with:
          build: npm run build
          start: npm run preview
